# Generated by Django 4.1.4 on 2023-02-03 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='S3_updatebucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_id', models.IntegerField()),
                ('s3_readupdate', models.CharField(max_length=20)),
                ('bucket_belonging_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s3_readupdate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='S3_mainbucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_id', models.IntegerField()),
                ('s3_mainname', models.CharField(max_length=20)),
                ('bucket_belonging_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s3_mainname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='S3_inputbucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_id', models.IntegerField()),
                ('s3_upload', models.CharField(max_length=20)),
                ('bucket_belonging_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s3_upload', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
